version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - shared-net

  alert-manager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - shared-net

  mqtt-exporter-gateway:
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    volumes:
      - ./config-gateway.yaml:/config.yaml
    ports:
      - 9640:9641

  mqtt-exporter-pole-1:
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    volumes:
      - ./config-1.yaml:/config.yaml
    ports:
      - 9641:9641

  mqtt-exporter-2:
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    volumes:
      - ./config-2.yaml:/config.yaml
    ports:
      - 9642:9641

  grafana:
    image: grafana/grafana
    user: "1000"
    networks:
      - shared-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    ports:
      - 3000:3000
networks:
  shared-net:
    driver: bridge