version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - shared-net

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - shared-net

  grafana:
    image: grafana/grafana
    user: "1000"
    networks:
      - shared-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    ports:
      - 3000:3000
networks:
  shared-net:
    driver: bridge
